name: EE274-proj
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - libcxx=20.1.8
  - libffi=3.4.4
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - python=3.10.19
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - contourpy==1.3.2
      - cycler==0.12.1
      - filelock==3.20.0
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.6
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - seaborn==0.13.2
      - six==1.17.0
      - sympy==1.14.0
      - torch==2.9.1
      - torchvision==0.24.1
      - typing-extensions==4.15.0
      - tzdata==2025.2
